@BASE_URL = http://laravel8x.homestead.test/api

###
# auth.register
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "name": "tester",
    "email": "abc123@abc.com",
    "password": "password",
    "password_confirmation": "password"
}

###
# @name login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "abc123@abc.com",
    "password": "password"
}

###
@access_token = {{login.response.body.access_token}}

###
# auth.me
GET {{BASE_URL}}/auth/me
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
# auth.logout
DELETE {{BASE_URL}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
# post.index
GET {{BASE_URL}}/posts
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "category_id": 2,
    "page": 1
}

###
# post.store
# @name post
POST {{BASE_URL}}/posts
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "category_id": 1,
    "title": "hello helper article",
    "body": "test write"
}

###
# @post_id = {{post.response.body.post.id}}
@post_id = 1

### 
# post.show
GET {{BASE_URL}}/posts/{{post_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
# post.update
PUT {{BASE_URL}}/posts/{{post_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "category_id": 1,
    "title": "modify post",
    "body": "modify test"
}

###
# post.delete
DELETE {{BASE_URL}}/posts/{{post_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 
# comment.create
# @name comment
POST {{BASE_URL}}/posts/{{post_id}}/comments
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "body": "my comment style is short!"
}

###
@comment_id = {{comment.response.body.post.comments[0].id}}

### 
# comment.destroy
DELETE {{BASE_URL}}/posts/{{post_id}}/comment/{{comment_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
# attachment.store
POST {{BASE_URL}}/attachments
Content-Type: multipart/form-data
Authorization: Bearer {{access_token}}


{
    "attachment_type": "posts",
    "attachment_id": {{post_id}}
}


###
# banner.index
GET {{BASE_URL}}/banners
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "category_id": 1
}

###
# banner.store
POST {{BASE_URL}}/banners
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "category_id": 1,
    "title": "my test banner",
    "link": "https://www.google.com/",
    "description": "my teacher is google"
}

